# Generated by Django 4.2.20 on 2025-05-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(default='something'),
            preserve_default=False,
        ),
    ]
